language: ruby
sudo: false
rvm:
  - ruby-head
  - 2.3.1
  - 2.2.5
os:
  - linux
matrix:
  fast_finish: true
  allow_failures:
  - rvm: ruby-head
script: bundle exec rake test
cache: bundler
env: TEST=true
notifications:
  slack:
    secure: OOP0jFNrVVXj/k7VQwMIjimYDZoOKatD4LHORmU8bYNUYCZdMUC1qp8MZ/TlLOx1+P9/SD0U8UWfGSQGOa0y9a5q0iQYCxDDjaJp612DOoLPO0sp4jRKmf7d2eERILZPgjQnsedyr9niKfJqqnBLFmqOVSpEpC6iWjLZeaQFcsg=
